### ISSUE TITLE
Homepage login button error

### ISSUE THREAD

**Issue by schmorrison** [henkie14/ionic2Firebase#1]
I am fairly new to Angular2 and very new to Ionic2 so I was following this [tutorial](https://chriztalk.com/ionic-2-and-firebase/). I made it to the middle of part 2 and I began receiving an error when clicking the "Login" button. Specifically:
```
Error in ./HomePage class HomePage - caused by: self.context.submit is not a function

TypeError: self.context.submit is not a function
    at CompiledTemplate.proxyViewClass.View_HomePage0.handleEvent_11 (/AppModule/HomePage/component.ngfactory.js:443:34)
    at CompiledTemplate.proxyViewClass.<anonymous> (http://localhost:8100/build/main.js:131314:37)
    at SafeSubscriber.schedulerFn [as _next] (http://localhost:8100/build/main.js:22323:36)
    at SafeSubscriber.__tryOrUnsub (http://localhost:8100/build/main.js:20115:16)
    at SafeSubscriber.next (http://localhost:8100/build/main.js:20064:22)
    at Subscriber._next (http://localhost:8100/build/main.js:20017:26)
    at Subscriber.next (http://localhost:8100/build/main.js:19981:18)
    at EventEmitter.Subject.next (http://localhost:8100/build/main.js:22826:25)
    at EventEmitter.emit (http://localhost:8100/build/main.js:22297:76)
    at FormGroupDirective.onSubmit (http://localhost:8100/build/main.js:28841:23)
    at Wrapper_FormGroupDirective.handleEvent (/ReactiveFormsModule/FormGroupDirective/wrapper.ngfactory.js:42:34)
    at CompiledTemplate.proxyViewClass.View_HomePage0.handleEvent_11 (/AppModule/HomePage/component.ngfactory.js:441:43)
    at CompiledTemplate.proxyViewClass.<anonymous> (http://localhost:8100/build/main.js:131314:37)
    at HTMLFormElement.<anonymous> (http://localhost:8100/build/main.js:56485:53)
    at t.invokeTask (http://localhost:8100/build/polyfills.js:3:10284)

```

```
Ionic Framework: 2.2.0
Ionic Native: 2.4.1
Ionic App Scripts: 1.1.4
Angular Core: 2.4.8
Angular Compiler CLI: 2.4.8
Node: 7.4.0
OS Platform: Linux 4.4
Navigator Platform: Linux x86_64
User Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/56.0.2924.76 Chrome/56.0.2924.76 Safari/537.36
```

This seems to be casused by the "ngSubmit" value on the home-page form element.

After removing the parts: ```(ngSubmit)="submit()" novalidate``` I began receiving the expected error of ```Uncaught (in promise): Error: There is no user record corresponding to this identifier. The user may have been deleted.```

Not sure why the error happened to me but seemingly no one else.

Thanks

schmorrison

**Comment by henkie14** [comment]
Hi schmorrison,
I can't reproduct the error, did you download the source code from GitHub or was it following the online tutorial?
